Repository bitcoinjs/bitcoinjs-lib, pull requests merged in 2018-07, with the labels that each got.

#1097 Use new payments within TransactionBuilder
  src/payments/p2ms.js
  src/payments/p2pk.js
  src/templates/witnessscripthash/input.js
  src/transaction_builder.js
  test/fixtures/transaction_builder.json
  test/integration/transactions.js
  test/transaction_builder.js
Labels: ready to merge, refactor

#1118 Provide directions to new-comers about how to find help
  README.md
Labels: how to / question / docs

#1119 rm Templates exports
  src/address.js
  src/classify.js
  src/index.js
  src/payments/p2pkh.js
  src/payments/p2sh.js
  src/payments/p2wpkh.js
  src/payments/p2wsh.js
  src/templates/multisig/input.js
  src/templates/multisig/output.js
  src/templates/pubkey/input.js
  src/templates/pubkey/output.js
  src/templates/pubkeyhash/input.js
  src/templates/pubkeyhash/output.js
  src/templates/scripthash/input.js
  src/templates/scripthash/output.js
  src/templates/witnesspubkeyhash/input.js
  src/templates/witnesspubkeyhash/output.js
  src/templates/witnessscripthash/input.js
  src/templates/witnessscripthash/output.js
  src/transaction_builder.js
  test/classify.js
  test/integration/bip32.js
  test/integration/cltv.js
  test/integration/crypto.js
  test/integration/csv.js
  test/integration/transactions.js
  test/templates.js
  test/transaction_builder.js
Labels: breaking change, how to / question / docs, ready to merge

#1127 Payments coverage tests (>90%)
  src/payments/p2ms.js
  src/payments/p2pkh.js
  src/payments/p2sh.js
  src/payments/p2wpkh.js
  test/fixtures/p2pkh.json
  test/fixtures/p2sh.json
  test/fixtures/p2wpkh.json
Labels: ready to merge, testing

#1129 testing/p2wsh: add missing test case coverage
  src/payments/p2wsh.js
  test/fixtures/p2wpkh.json
  test/fixtures/p2wsh.json
  test/payments.utils.js
Labels: ready to merge, testing

#1130 Update CHANGELOG
  CHANGELOG.md
Labels: how to / question / docs, ready to merge

#1132 Remove Node 6, update to Node LTS
  .travis.yml
  package.json
Labels: breaking change, external

#1133 tests: add bare P2W* integration tests (and fix a bug)
  README.md
  src/transaction_builder.js
  test/fixtures/transaction_builder.json
  test/integration/transactions.js
Labels: bug, ready to merge, testing

#1134 fix example links of README.md
  README.md
Labels: how to / question / docs

#1135 Add additional payments integration tests
  src/transaction_builder.js
  test/integration/_regtest.js
  test/integration/payments.js
  test/integration/transactions.js
Labels: ready to merge, testing

#1139 4.0.1 | bump dependencies to 1.0.0 versions (and simplify Travis)
  .travis.yml
  CHANGELOG.md
  package.json
  test/integration/crypto.js
Labels: external, ready to merge
