Repository bitcoinjs/bitcoinjs-lib, pull requests merged in 2018-12, with the labels that each got.

#1228 README: add usage notes
  CHANGELOG.md
  README.md
  test/integration/addresses.js
  test/integration/crypto.js
  test/integration/stealth.js
Labels: how to / question / docs

#1086 Move Transaction to ES6 class syntax
  src/transaction.js
Labels: ready to merge, refactor

#1307 Fix some small bugs
  src/payments/p2ms.js
  src/transaction_builder.js
  test/fixtures/p2ms.json
Labels: bug

#1279 add P2SH(P2WPKH) signature verification example
  test/integration/transactions.js
Labels: how to / question / docs, testing
